# Generated by Django 4.1.4 on 2023-05-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_upload_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert'), ('SHARPEN', 'sharpen'), ('MEDIAN', 'median'), ('NOISE_REDUCTION', 'noise reduction')], max_length=50),
        ),
    ]
