# Generated by Django 4.1.7 on 2023-06-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cartorder_sku_alter_cartorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
