# Generated by Django 4.1.7 on 2023-06-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cartorder_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='sku',
        ),
    ]
