# Generated by Django 4.1.7 on 2023-06-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cartorder_price_alter_cartorderproducts_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default='3.00', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default='3.00', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='total',
            field=models.DecimalField(decimal_places=2, default='3.00', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='5.00', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='3.00', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='upload',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'NO FILTER'), ('IMPROVE_RESOLUTION', 'IMPROVE RESOLUTION'), ('LOW_LIGHT_ENHANCE', 'LOW LIGHT ENHANCE')], max_length=50),
        ),
    ]
